### ISSUE TITLE
The source code for lambda functions is not present in simple-ssr/edge-build folder

### ISSUE THREAD

**Issue by sachin10101998** [aws-samples/react-ssr-lambda#1]
The lambda code referenced in the cdk part doesn't exist in respective folders

**Comment by roman-boiko** [comment]
This code is generated by webpack during build phase.
You need to build simple-ssr project before deploying it with AWS CDK.
You should run the next commands
cd ../simple-ssr
npm install
npm run build-all
cd ../cdk
cdk deploy SSRAppStack --parameters mySiteBucketName=<your bucket name>
