### ISSUE TITLE
Data is loaded again (unnecessarily) after hydration

### ISSUE THREAD

**Issue by jakke-korpelainen** [aws-samples/react-ssr-lambda#16]
Hey,

I'm running a working implementation of a solution based on this stack. However I've now run into a slight issue that the static result hydrated by React is loading the same information again.

https://github.com/aws-samples/react-ssr-lambda/blob/8c57f9d5343e78213a8cec1ff3d1f1d41c5932fa/simple-ssr/src/App.js#L9

In the <App/> props there is isSSR and ssrData, but I'm not finding references that it those are used from anywhere. I'm aware that this might not be an issue related strictly to this sample but would be interested in how and if you've solved this somehow.

**Comment by roman-boiko** [comment]
Will be updated in a new sample I am working currently on
