### ISSUE TITLE
Module not found: Can't resolve './config.json'

### ISSUE THREAD

**Issue by rajkumarks7** [aws-samples/react-ssr-lambda#3]
when i run the npm start inside the simple-ssr
Module not found: Can't resolve './config.json'

**Comment by roman-boiko** [comment]
The config.json is generated by the first stack and contains the url to the API Gateway.
Before running npm start please run the next comands
cd react-ssr-lambda

cd ./cdk

npm install

npm run build

cdk bootstrap

cdk deploy SSRApiStack --outputs-file ../simple-ssr/src/config.json
